# Generated by Django 2.0.2 on 2018-02-09 05:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('custom_manager', '0002_childc'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='childb',
            managers=[
                ('default_manager_name', django.db.models.manager.Manager()),
            ],
        ),
    ]
