# Generated by Django 2.0.2 on 2018-02-09 05:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('custom_manager', '0003_auto_20180209_1445'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='childb',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='childc',
            managers=[
                ('extra_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
