# Generated by Django 2.0.2 on 2018-02-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_manager', '0004_auto_20180209_1457'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='childc',
            managers=[
            ],
        ),
    ]
