# Generated by Django 2.0.2 on 2018-02-06 05:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0006_auto_20180206_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 2, 6, 5, 36, 11, 244638, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('from_user', 'to_user')},
        ),
    ]
